configDate: 11/29/2005
vcenterInfo:
    -   vcenter_ip: 10.0.31.251
        vcenter_user: admin
        vcenter_passwd: Sugon!123
        vcenter_token: ee7f7b7dd5cd445855bef6a070ae9ad9
    -   vcenter_ip: 10.0.36.128
        vcenter_user: admin
        vcenter_passwd: Sugon!123
        vcenter_token: bb4b246da8f446ed12c529374a5e29a1
        